package Main;

import javax.swing.*;

class GUI extends JFrame {

    //Attributes used by configuration object
    private String language, inputPath, outputPath, nGramType;
    private int nGramLength;
    private boolean sortAlphabetically;

    GUI() {
        initComponents();
        chooser = new JFileChooser();
        sortAlphabetically = false;
    }


    //Code generated by netbeans; create and display components
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOut = new javax.swing.JTextArea();
        jButtonGetInputFile = new javax.swing.JButton();
        jButtonGetOutputFile = new javax.swing.JButton();
        jLabelLang = new javax.swing.JLabel();
        jComboBoxLang = new javax.swing.JComboBox<>();
        jLabelLang1 = new javax.swing.JLabel();
        jComboBoxSize = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonChar = new javax.swing.JRadioButton();
        jRadioButtonWords = new javax.swing.JRadioButton();
        jToggleButtonSearch = new javax.swing.JToggleButton();
        jCheckBoxSortAlphabetically = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaOut.setEditable(false);
        jTextAreaOut.setColumns(20);
        jTextAreaOut.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOut);

        jButtonGetInputFile.setText("Select Input File");
        jButtonGetInputFile.addActionListener(this::jButtonGetInputFileActionPerformed);

        jButtonGetOutputFile.setText("Select Output File");
        jButtonGetOutputFile.addActionListener(this::jButtonGetOutputFileActionPerformed);

        jLabelLang.setText("Enter Language:");

        jComboBoxLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EN-GB", "DE-DE", "DA-01", "EL-01", "ES-ES", "FI-01", "FR-FR", "IT-IT", "NL-NL", "PT-PT", "SV-SE", "LV-01", "CS-01", "ET-01", "PL-01", "SL-01", "LT-01", "MT-01", "SK-01", "BG-01" }));

        jLabelLang1.setText("Enter Size:");

        jComboBoxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel1.setText("Select Type:");

        buttonGroup1.add(jRadioButtonChar);
        jRadioButtonChar.setSelected(true);
        jRadioButtonChar.setText("Chars");

        buttonGroup1.add(jRadioButtonWords);
        jRadioButtonWords.setText("Words");

        jToggleButtonSearch.setText("Search");
        jToggleButtonSearch.addActionListener(this::jToggleButtonSearchActionPerformed);

        jCheckBoxSortAlphabetically.setText("Sort Alphabetically");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(jLabelLang1))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jComboBoxSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jComboBoxLang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jCheckBoxSortAlphabetically)
                                                                        .addComponent(jToggleButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jButtonGetInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jRadioButtonWords)
                                                                        .addComponent(jRadioButtonChar)
                                                                        .addComponent(jLabel1)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jLabelLang))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButtonGetOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGetInputFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonGetOutputFile)
                                .addGap(24, 24, 24)
                                .addComponent(jLabelLang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabelLang1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonChar)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonWords)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxSortAlphabetically)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButtonSearch)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>

    //Create a file chooser object
    private String createFileChooser(String title){
        //Set the default directory of the file chooser to the directory of project
        chooser.setCurrentDirectory(new java.io.File(System.getProperty("user.dir")));
        chooser.setDialogTitle(title);
        //Only allow users to select folders
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);// disable the "All files" option
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            return chooser.getSelectedFile().toString();//Return the directory of the selected file
        }
        else {
            //If nothing is selected display warning and return null
            JOptionPane.showMessageDialog(this,"No input file specified"," Warning", JOptionPane.WARNING_MESSAGE);
            return null;
        }
    }

    private void jButtonGetInputFileActionPerformed(java.awt.event.ActionEvent evt) {
        inputPath=createFileChooser("Select Input File");

    }

    private void jButtonGetOutputFileActionPerformed(java.awt.event.ActionEvent evt) {
        outputPath = createFileChooser("Select Output File");
}



    private void jToggleButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {
        //Check if a file has been selected
        if (inputPath==null)
            JOptionPane.showMessageDialog(this,"No input file specified"," Warning", JOptionPane.WARNING_MESSAGE);
        if (outputPath==null)
            JOptionPane.showMessageDialog(this,"No output file specified"," Warning", JOptionPane.WARNING_MESSAGE);
        else{
            if(jCheckBoxSortAlphabetically.isSelected()){
                sortAlphabetically = true;
               // outputPath = System.getProperty("user.dir")+"/intermediate";
            }
            else {
                sortAlphabetically = false;
               // outputPath = System.getProperty("user.dir")+"/output";
            }
            //Clear the text area
            jTextAreaOut.setText("");
            //Get the selected language from the language combo box
            language=jComboBoxLang.getSelectedItem().toString();
            //Get the selected n gram length from the size combo box
            nGramLength=Integer.parseInt(jComboBoxSize.getSelectedItem().toString());
            //Determine what type of ngram the user is looking for
            if(jRadioButtonChar.isSelected())
                nGramType = "c";
            else
                nGramType = "w";
            Main.startJob();

        }
    }

    String getInputPath() {
        return inputPath;
    }

    String getOutputPath() {
        return outputPath;
    }

    int getnGramLength() {
        return nGramLength;
    }

    String getnGramType() {
        return nGramType;
    }

    String getLanguage() {
        return language;
    }

    JTextArea getjTextAreaOut() {
        return jTextAreaOut;
    }

    boolean getIsSortAlphabetically() {
        return sortAlphabetically;
    }

    private JFileChooser chooser;
    private javax.swing.JButton jButtonGetInputFile;
    private javax.swing.JButton jButtonGetOutputFile;
    private javax.swing.JComboBox<String> jComboBoxLang;
    private javax.swing.JComboBox<String> jComboBoxSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLang;
    private javax.swing.JLabel jLabelLang1;
    private javax.swing.JRadioButton jRadioButtonChar;
    private javax.swing.JRadioButton jRadioButtonWords;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOut;
    private javax.swing.JToggleButton jToggleButtonSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBoxSortAlphabetically;

    // End of variables declaration


}
